on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
name: "Build & Release"
jobs:
  build:
    name: Release APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - name: Pub Get Packages
        run: flutter pub get

      - name: Generate Schema
        run: flutter pub run build_runner build

      - name: Setup envfile
        run: echo GRAPHQL_SERVER_HOST=${{ secrets.GRAPHQL_SERVER_HOST }} >> .env

      - name: Setup keys
        run: |
          echo storePassword=${{ secrets.KEYSTORE_PASSPHRASE }} >> ./android/key.properties
          echo keyPassword=${{ secrets.KEYSTORE_PASSPHRASE }} >> ./android/key.properties
          echo keyAlias=upload >> ./android/key.properties
          echo storeFile=../key.jks >> ./android/key.properties
          echo "${{ secrets.JKS_KEY }}" > key.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch key.jks.asc > ./android/key.jks


      - name: Build APK
        run: flutter build apk --split-per-abi --release --verbose

      - name: Build APPBUNDLE
        run: flutter build appbundle --release

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
